# Sentinel Configuration File
# ---------------------------

# Ruta de los logs a analizar
LOG_PATH="/var/log/auth.log"

# Critical Paths:

RUTAS_CRITICAS="/tmp|/dev/shm|/var/tmp"

# Umbral de intentos fallidos para activar alerta
AUTH_THRESHOLD=5

# Carpeta para reportes
REPORT_DIR="./reports"

# ID de sistema personalizado 
CUSTOM_SYS_ID=""

# Configuración de Auditoria de Permisos
# -------------------------------------
# Binarios SUID conocidos y seguros
PERM_WHITELIST="/usr/bin/passwd /usr/bin/sudo /usr/bin/chsh /usr/bin/mount /usr/bin/umount /usr/bin/su /usr/bin/gpasswd /usr/bin/chfn /usr/bin/pkexec"

# Rutas donde buscar archivos de configuracion y secretos
AUDIT_PATHS="/etc /home /var/www"

